/**
 * Refreshes src/data/cpiHistory.ts, the built-in inflation data the app uses until the live copy
 * arrives, on hosts without the Netlify function (plain `vite dev`), and whenever FRED is down.
 *
 * Run it now and then, for example after each monthly CPI release: `node scripts/update-cpi.mjs`.
 * It uses the same parsing as the inflation function, so both always agree.
 */
import { writeFile } from "node:fs/promises";
import { fetchInflationData } from "../netlify/lib/fred.mts";

const data = await fetchInflationData();
const annual = data.annual.map(([year, index]) => `[${year}, ${index}]`).join(", ");

const source = `// Generated by scripts/update-cpi.mjs from FRED on ${data.fetchedAt.slice(0, 10)}. Don't edit by hand;
// rerun the script to refresh it.
import type { InflationData } from "../lib/inflation.ts";

/** US inflation data built into the app, used until live data loads and whenever it can't. */
export const BUILT_IN_INFLATION: InflationData = {
  annual: [${annual}],
  latest: ${JSON.stringify(data.latest)},
  market: ${JSON.stringify(data.market)},
  fetchedAt: ${JSON.stringify(data.fetchedAt)},
};
`;

await writeFile(new URL("../src/data/cpiHistory.ts", import.meta.url), source);
console.log(
  `update-cpi: ${data.annual.length} years to ${data.annual.at(-1)[0]}, latest ${data.latest.date} ` +
    `(${(data.latest.yoy * 100).toFixed(2)}% a year), breakeven ${(data.market.breakeven10y * 100).toFixed(2)}%`,
);
